export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const LOGIN_AND_FETCH_CURRENT_USER = "LOGIN_AND_FETCH_CURRENT_USER";

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";

export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const DELETE_USER = "DELETE_USER";
export const CREATE_USER = "CREATE_USER";
export const FETCH_TAG_LIST = "FETCH_TAG_LIST";
export const FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST";
export const FETCH_COMMENT_LIST = "FETCH_COMMENT_LIST";
